Implemented statistics
PNUdev/communal-property-registry pull request #18
Opened 2021-02-23 21:03 UTC by MrZenik

2021-02-24 18:12 UTC, SerhiiKlymchuk commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +    private final CategoryByPurposeRepository categoryByPurposeRepository;
empty line between fields.

2021-02-24 18:20 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyStatisticDto.java
> +    private int numberOfUsedByCityCouncil;
I think you should use object type instead of primitive one.

2021-02-24 18:21 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/repository/CategoryByPurposeRepository.java
> +
There is no need for this method, because they're already available in CrudRepository interface.

2021-02-24 18:21 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyRepository.java
> +
The same here

2021-02-24 18:24 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +
Please, replace generic foreach statement with foreach from streams, it will increase readability of your code.

2021-02-24 18:30 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +                .count();
It will be better if you remove this method from service and put it in repository PropertyRepository. It will increase performance.

`Long countPropertiesByCategoryByPurposeIdEqualsAndPropertyStatusEquals(
 Long categoryByPurposeId, 
 Property.PropertyStatus propertyStatus)`

And also there is no need to make this method public if it won't be used outside of service.

2021-02-24 18:41 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +
Or just replace for `categories.foreach()` without streams

2021-02-24 19:02 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +                .count();
I think it isn't good, because there will be N * 5 more queries in the database for one call to the `getStatistic()` method

2021-02-24 19:06 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +    public int getNumberOfRepetitions(List<Property> properties, Long categoryId,
You should make this method @Override or make private and delete him from repository

2021-02-24 20:39 UTC, MarrMika requested changes
Good start, but your statistics-gathering approach has a negative impact on efficiency. We need to improve it by reducing calls to DB!

Let's look at this example! Try to use this query or even improve this one.
![image](https://user-images.githubusercontent.com/33421961/109073772-8846a000-76ff-11eb-8c5b-f4686c6b53d8.png)

2021-02-24 20:39 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyStatisticResponseDto.java
> +    List<PropertyStatisticDto> propertyStatistic;
Let's follow the general style. Please, rename to `propertyStatistics`

2021-02-24 20:39 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/repository/CategoryByPurposeRepository.java
> +
Please, delete this empty line

2021-02-24 20:39 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +
In fact, in this method, you will make `(categories.size()*5) +2` calls to DB to prepare statistics. It is rather bad for performance. 
I propose you make replace this countPropertiesByCategoryByPurposeIdEqualsAndPropertyStatusEquals() with programatic approach or enhace it at DB level using `group by` statement

2021-02-24 21:01 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +    @GetMapping("/statistics")
`/statistic`

2021-02-24 21:02 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +public class StatisticServiceImpl implements StatisticService{
space before `{`

2021-02-24 22:23 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +
Correct, all this calculations should be performed using one custom query

2021-02-24 22:24 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +        List<Property> properties = (List<Property>) propertyRepository.findAll();
Do not perform casting here. Just create a corresponding method in repository

2021-02-24 22:25 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +@RequestMapping("/api")
`/api/statistics`

2021-02-25 11:00 UTC, vanya706 approved these changes
Good job!

2021-02-25 17:11 UTC, MarrMika reviewed
Have you verified new changes with your teammate again?

2021-02-25 17:18 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +        return new PropertyStatisticResponseDto(propertyRepository.getListOfStatistic());
Please, add some logs over here, at least one in the service method. Just place @Slf4j at class and use log.debug()

2021-02-25 18:21 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyStatisticResponseDto.java
> +    List<PropertyStatisticDto> propertyStatistics;
make this field `private`

2021-02-25 18:23 UTC, volodymyrvynnyk requested changes
LGTM, one comment to fix

2021-02-25 20:32 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +
Property statistic gathering started!

2021-02-25 20:33 UTC, MarrMika approved these changes

2021-02-26 16:12 UTC, Igor-Polatajko requested changes

2021-02-26 16:12 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +    public StatisticService statisticService;
private

2021-02-26 16:12 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +public class PropertyController {
StatisticsController

2021-02-26 16:12 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyStatisticDto.java
> +    private Long numberOfListed;
`numberOfFirstOrSecondType` or smth like this

2021-02-26 16:12 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +    public PropertyStatisticResponseDto getStatistic(){
Stick to `statistic` or `statistics` everywhere. Do not use both.
I propose to use `statistics`

2021-02-26 16:12 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/StatisticServiceImpl.java
> +        log.debug("Property statistics collection has started!");
log.info("Get property statistics request");

It doesn't start a backgroud job to say, that it "started".

2021-02-26 16:20 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyStatisticResponseDto.java
> +@Builder
seems like we don't need builder for this class

2021-02-26 16:20 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyStatisticDto.java
> +public class PropertyStatisticDto {
the same: seems like we don't need builder for this class

2021-02-26 17:51 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyRepository.java
> +            "FROM category_by_purpose as cbp, property as p " +
Why not?
```
FROM category_by_purpose as cbp JOIN property as p 
ON cbp.id = p.category_by_purpose_id
```

2021-02-26 18:06 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyRepository.java
> +            "FROM category_by_purpose as cbp, property as p " +
Basically, it's the same!

2021-02-26 18:24 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyRepository.java
> +            "FROM category_by_purpose as cbp, property as p " +
This query is equivalent to INNER JOIN (execution plans have to be the same, I believe). But, in case of inner join, it will return nothing for the category without properties.
As for me JOIN is little bit more readable and obvious, even if we compare this two ways of performing INNER JOIN.

2021-02-26 18:27 UTC, Igor-Polatajko approved these changes
Looks good!

2021-02-26 18:29 UTC, merged