[PNUDEV-1] Implement application public page
PNUdev/communal-property-registry pull request #19
Opened 2021-03-02 16:37 UTC by SerhiiKlymchuk

![image](https://user-images.githubusercontent.com/62187026/109681216-ece17f00-7b85-11eb-9773-856ca02fe375.png)

2021-03-02 17:27 UTC, Igor-Polatajko commented on src/main/resources/templates/main/main.ftl
> +                    <option value="school">Школа</option>
Hardcode??

2021-03-02 17:27 UTC, MrZenik commented on src/main/resources/templates/main/main.ftl
> +                        <td>{{stat.numberOfListed}}</td>
`numberOfFirstOrSecondType`

2021-03-02 17:33 UTC, Igor-Polatajko commented on src/main/resources/static/js/main.js
> +                .catch(error => console.error(error))
Some message, that we unable to load the data should be displayed in the block

2021-03-02 17:33 UTC, Igor-Polatajko commented on src/main/resources/static/js/main.js
> +                .then(error => console.error(error))
same

2021-03-02 17:33 UTC, Igor-Polatajko commented on src/main/resources/static/js/main.js
> +                .catch(error => console.error(error))
same

2021-03-02 17:33 UTC, Igor-Polatajko commented on src/main/resources/static/js/map.js
> +        .catch(error => console.error(error))
same

2021-03-02 18:04 UTC, Igor-Polatajko commented on src/main/resources/templates/main/main.ftl
> +                    <option value="all">Будь-яка категорія</option>
Actually, nothing wrong with rendering it on the client as well
It will allow us not to create web controller for this page at all
Just create REST endpoint to load names and ids for all categories and render them on the client: `<option value="{{ category.id }}">{{ category.name }}</option>`

2021-03-03 20:44 UTC, SerhiiKlymchuk commented on src/main/resources/templates/main/main.ftl
> +                    <option value="all">Будь-яка категорія</option>
`category.id` as a value will brake Arthur's code

2021-03-03 21:26 UTC, MarrMika approved these changes
Quite impressive work! Could please make the width of the status labels constant for every property? I mean this one 
![image](https://user-images.githubusercontent.com/33421961/109874408-c3088500-7c77-11eb-8757-d0c3e2a14ac9.png)

2021-03-03 21:26 UTC, MarrMika commented on src/main/resources/static/js/main.js
> +        },
Do we need this comment?

2021-03-03 21:26 UTC, MarrMika commented on src/main/resources/templates/main/main.ftl
> +            </div>
I do believe it should be a post request with additional params. @Igor-Polatajko, am I right? Or will we do it in the next task?

2021-03-03 22:07 UTC, Igor-Polatajko commented on src/main/resources/templates/main/main.ftl
> +            </div>
Correct
Query parameters have to be added

2021-03-03 22:07 UTC, Igor-Polatajko commented on src/main/resources/static/js/map.js
> +    axios.get('/api/property/map-locations')
Check endpoints URLs in the task
They were updated

2021-03-03 22:07 UTC, Igor-Polatajko commented on src/main/resources/static/js/main.js
> +                .catch(error => {
This shouldn't be a log to console
Proper message should be shown on the UI
For all places like this

2021-03-03 22:07 UTC, Igor-Polatajko commented on src/main/resources/static/js/main.js
> +            axios.get('/api/category-by-purpose')
Let's stick to plural form
categories-by-purpose

2021-03-03 22:07 UTC, Igor-Polatajko commented on src/main/resources/templates/main/main.ftl
> +                    <option v-for="cat in categories" :value="cat.name" v-model="categories">
Are we sure, that all the names will be always url safe?

2021-03-03 22:07 UTC, Igor-Polatajko commented on src/main/resources/templates/main/main.ftl
> +                    <option v-for="cat in categories" :value="cat.name" v-model="categories">
If no, then, maybe, using id here would be better choice

2021-03-03 22:17 UTC, Igor-Polatajko commented on src/main/resources/static/js/main.js
> +                .catch(error => {
Actually, for simplicity, let's leave it as is.
In the case of error, data just won't be displayed.
That's ok for now.
Chances of such errors are really low, because, single db is used for single app. So, in will either work or not work as a whole, without partial failures.

2021-03-03 22:21 UTC, SerhiiKlymchuk commented on src/main/resources/static/js/main.js
> +        },
yep, on every change of the url,  we update the properties. It'll be uncommented as soon as backend will arrive

2021-03-04 07:40 UTC, MarrMika commented on src/main/resources/static/js/main.js
> +        },
thanks

2021-03-04 07:40 UTC, MarrMika commented on src/main/resources/templates/main/main.ftl
> +            </div>
thanks!

2021-03-05 19:59 UTC, MrZenik approved these changes

2021-03-05 20:32 UTC, vanya706 approved these changes
Great work!

2021-03-06 11:20 UTC, Igor-Polatajko approved these changes
Great work!!!
Few comments

2021-03-06 11:20 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/CategoryByPurposeController.java
> +    private CategoryByPurposeService categoryByPurposeService;
Where is the service itself?

2021-03-06 11:20 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/CategoryByPurposeController.java
> +        return categoryByPurposeService.getCategories();
should be `categoryByPurposeService.findAll` by convention

2021-03-06 11:20 UTC, Igor-Polatajko commented on src/main/resources/static/js/map.js
> +            resp.data.forEach(d=>{
maybe `propertyLocationData` instead of `d`?

2021-03-06 11:20 UTC, Igor-Polatajko commented on src/main/resources/static/js/map.js
> +            .find(m => m.id === propertyId+'')
Naming & formatting
Don't use one char names, because it's harder to read, even if the scope of variable is small

2021-03-07 11:34 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/CategoryByPurposeResponseDto.java
> +    private List<CategoryByPurpose> categoriesByPurpose;
Returning dto, instead of domain model would be better.
But, it can be as it is, because, it's simple object and we have nothing to "hide" here, so no need to increase complexity.

2021-03-07 12:52 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +                .antMatchers("/css/main.css", "/js/**").permitAll()
Add main page to "permit all" section

2021-03-07 12:53 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +                .defaultSuccessUrl("/", true)
Default success url should point to admin panel

2021-03-07 12:56 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +                .antMatchers("/css/main.css", "/js/**").permitAll()
Also, add all API endpoints that main page calls to "permit all" section

2021-03-08 14:09 UTC, vanya706 commented on src/main/resources/templates/main/main.ftl
> +                    <option value="USED_BY_COUNCIL">Вик. міськвладою</option>
`USED_BY_COUNCIL` change this to correct form `USED_BY_CITY_COUNCIL`
![image](https://user-images.githubusercontent.com/57075862/110332139-a0d08780-8028-11eb-8755-aab148d68740.png)

2021-03-08 14:11 UTC, vanya706 commented on src/main/resources/static/js/map.js
> +    USED_BY_COUNCIL: "rgb(174,152,229)"
and here, please, change to correct form

2021-03-08 14:12 UTC, vanya706 requested changes
Some comments

2021-03-08 16:00 UTC, vanya706 approved these changes
Now, it's perfect for me!

2021-03-08 16:10 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +                .defaultSuccessUrl("/admin/admin", true)
I believe it should be just "/admin"

2021-03-08 16:10 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +                .antMatchers("main/main", "/api/statistics", "/api/properties/**",
There is no "/main/main", just "<empty>" or "/"

2021-03-08 16:10 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +        http
I think, it's better to add all urls explicitly, without **

2021-03-09 19:44 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/SecurityConfig.java
> +                .antMatchers(
actually, let's make stuff under `/admin` to require authentication
everything else have to by publicly available

2021-03-10 17:56 UTC, merged