[PNUDEV-2] Implement property REST endpoints
PNUdev/communal-property-registry pull request #20
Opened 2021-03-03 12:41 UTC by pikulo-kama

2021-03-03 22:06 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +    }
Throws keyword is used for handling checked exceptions. ServiceException is unchecked

2021-03-04 09:12 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +
You're right.
Any filtering or search related query parameter can be absent, as well as all of them. In such case we have to show all the properties (obviously, with pagination).

2021-03-04 10:16 UTC, SerhiiKlymchuk commented on src/main/java/com/pnudev/communalpropertyregistry/domain/Property.java
> +        private String ukrainian_representation;
ukraininan representation is redundant, because it's handled on frontend

2021-03-04 11:49 UTC, SerhiiKlymchuk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +            @Nullable @RequestParam(name = "q") String searchQuery,
rename `(name='p') Integer page,` to `(name='page') Integer page, `

2021-03-04 13:22 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ServiceException.java
> +public class ServiceException extends RuntimeException {
there is should be new line

2021-03-04 13:23 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ServiceException.java
> +}
and new line before `}`

2021-03-04 17:56 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +
I don't quite understand. How can I validate that page number is positive using Optional?

2021-03-04 18:26 UTC, SerhiiKlymchuk approved these changes
Good job!

2021-03-04 18:34 UTC, MrZenik commented on src/main/java/com/pnudev/communalpropertyregistry/repository/CategoryByPurposeRepository.java
> +    CategoryByPurpose findByName(String name);
Is this method used somewhere?

2021-03-04 18:40 UTC, MrZenik commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeService.java
> +}
new line after method

2021-03-04 20:30 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyToPropertyResponseDtoMapper.java
> +    private final CategoryByPurposeRepository categoryByPurposeRepository;
https://github.com/SerhiiKlymchuk/gmail-pet/pull/9#discussion_r559477373

2021-03-04 20:30 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyToPropertyResponseDtoMapper.java
> +}
same, put here new line and in another places as well, please

2021-03-05 08:13 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +@RequestMapping(value = "/api/property")
Mapping should be in plural `/api/properties`

2021-03-05 08:16 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +            @Nullable @RequestParam(name = "page") Integer page,
You can skip `@Nullable` and use `default value of param = 0`

2021-03-05 08:20 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/AttachmentRepository.java
> +    List<Attachment> findAttachmentsByPropertyIdEquals(Long propertyId);
That`s should work to use just `findAttachmentsByPropertyId(Long propertyId)`

2021-03-05 08:35 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentServiceImpl.java
> +                attachmentRepository.findAttachmentsByPropertyIdEquals(id))
Can `attachmentRepository.findAttachmentsByPropertyIdEquals(id)` return `null`? Or just empty list?

2021-03-05 08:38 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +                .map(propertyService.findById(id));
Let's use mapper in service layer

2021-03-05 08:39 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +import static com.pnudev.communalpropertyregistry.domain.QProperty.property;
I cannot find this class in your branch, take a look whether you added it into commit

2021-03-05 08:43 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +        }
I'm not sure, but probably when page number in Pageable is negative, exception will be thrown by Repository, verify it please
And it's not the best approach to throw `ServiceException` from `Controller layer`

2021-03-05 08:43 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyService.java
> +    Property findById(Long id);
Return `PropertyResponseDto`

2021-03-05 08:46 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/FlashMessageConstants.java
> +    public static final String ERROR_FLASH_MESSAGE = "error_flash_message";
You can replace it using enums

2021-03-05 08:48 UTC, volodymyrvynnyk commented on src/main/resources/application.yaml
> +rest.pagination.size: 5
rename it to something like `rest.properties.pagination.size` to make it understandable where it is used

2021-03-05 08:50 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyToPropertyResponseDtoMapper.java
> +        AttachmentResponseDto attachmentResponseDto = null;
Remove this line
and look comments below

2021-03-05 08:50 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyToPropertyResponseDtoMapper.java
> +        return attachmentResponseDto;
return null

2021-03-05 08:51 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyToPropertyResponseDtoMapper.java
> +            attachmentResponseDto = AttachmentResponseDto.builder()
return AttachmentResponseDto.builder() ...

2021-03-05 08:53 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyToPropertyResponseDtoMapper.java
> +public class PropertyToPropertyResponseDtoMapper {
I'd like it renamed to simple `PropertyMapper` 
And than rename mapping methods to something like `mapToResponseDto`, `mapToResponseDtoList` etc

2021-03-05 08:54 UTC, volodymyrvynnyk requested changes
Good job, but some edits required

2021-03-05 09:03 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyDslRepositoryImpl.java
> +    }
Probably, you missed @Autowired

2021-03-05 10:47 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyDslRepositoryImpl.java
> +    }
In this case, it will work without `@Autowired`, It's probably required for better readability?

2021-03-05 14:42 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyDslRepositoryImpl.java
> +                .imageUrl(tuple.get(property.imageUrl))
I found bug in my code and fix it, I see you have the same bug [https://github.com/PNUdev/communal-property-registry/pull/21/commits/f827438df18aeee1ac3cf580eb1a14b5dde6e357](url)

2021-03-07 18:24 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +    private final PropertyLocationDslRepository propertyLocationDslRepository;
Is this field used?

2021-03-07 18:29 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/dsl/PropertyLocationDslRepositoryImpl.java
> +    public PropertiesLocationsResponseDto findAllMapLocations(Predicate... where) {
As far as this class is repo, return `properties` from method, and map it to dto in service layer

2021-03-07 18:30 UTC, volodymyrvynnyk approved these changes
One comment to fix, everything else looks for me

2021-03-08 20:27 UTC, vanya706 approved these changes
Great Job!

2021-03-09 13:37 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +}
Why not define findAll() method in AttachmentCategoryRepository ?

(It's nice that you want to use Spliterator,  but there it's not critically needed.
For instance, Java collection classes provide default parallelStream() method which internally uses the Spliterator through the call to the spliterator() 
```
StreamSupport.stream(all.spliterator(), true)  ====  parallelStream()
```
I advise you to use explicitly spliterator() explicitly when you want to break data into small streams and handle them or process operation on them using extra Spliterator features)

2021-03-09 13:37 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +
Ukrainian representation?

2021-03-09 13:37 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +            }
Вказана категорія не існує!

2021-03-09 13:37 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +
Приміщення не знайдено!

2021-03-09 13:37 UTC, MarrMika commented on src/main/resources/application.yaml
> +rest.properties.pagination.size: 5
Left comment about this key in https://github.com/PNUdev/communal-property-registry/pull/23
In the case of PropertyController, it works but not in PR-23
Just think it over how to improve the name of the key

2021-03-09 19:41 UTC, Igor-Polatajko requested changes

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/domain/Property.java
> -        NON_RENT, RENT, FIRST_OR_SECOND_TYPE_LIST, PRIVATIZED, USED_BY_CITY_COUNCIL
do not change formattings if you don't change code
it makes harder to get in scope of which task the change was made

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ExceptionInterceptor.java
> +public class ExceptionInterceptor {
mvc controller for rest api exceptions?

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ServiceException.java
> +public class ServiceException extends RuntimeException {
there should be different exceptions for admin panel, for rest api and for file downloading
so that they can be handled properly
in this case, it have to be `ServiceApiException`

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/dsl/PropertyDslRepositoryImpl.java
> +    public List<Property> findAll(Predicate... where) {
Do not change that method, it was written the way it supposed to be
We don't need method that return whole object

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/dsl/PropertyDslRepositoryImpl.java
> +    private Property mapTupleToProperty(Tuple tuple) {
this have to be in the mapper

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/dsl/QueryDslRepository.java
> +    default OrderSpecifier[] getOrderSpecifiers(Pageable pageable, Class<?> aClass) {
what is this method for?
do we need it of we can write it in simpler way?

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/dsl/QueryDslRepository.java
> +public interface QueryDslRepository<T> {
We don't need generic dsl repository.
Only PropertyRepository have to be powered by dsl

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        Iterable<AttachmentCategory> all = attachmentCategoryRepository.findAll();
all method to reposotory, that will return List

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        List<Property> properties = propertyDslRepository
Only required fields have to be fetched, not all of them

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        BooleanExpression predicate = property.id.isNotNull();
Use the list of predicated, as it was used in @MrZenik 's PR to keep sigle style

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +                Property.PropertyStatus status = Property.PropertyStatus.valueOf(propertyStatus.toUpperCase());
https://github.com/PNUdev/radio-service/blob/master/radio-service-api/src/main/java/com/pnu/dev/radioserviceapi/mongo/DayOfWeek.java#L27

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/FlashMessageConstants.java
> +public enum FlashMessageConstants {
why do we need flash attributes in scope of this PR?

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    public PropertyLocationDto mapToPropertyLocationDto(Property property) {
Leave this method the way it was

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +        List<AttachmentCategory> categories = attachmentCategoryService.findAll();
Still n+1 query, because we will be executing it for each property.

You can query all the relevant properties (`findAll`) and all the relevant attachements (`findAllByPropertyIdIn`), grouped by categories using two queries, and perform smart mapping on Java.

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                .filter((a) -> a.getAttachmentCategoryId().equals(attachmentCategory.getId())
do not name variables by single character, even if the scope is small

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                .attachments(categories.stream()
this inner stream have to be in separate method

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    public PropertyResponseDto mapToPropertyResponseDto(Property property) {
You can map from `tuple` directly here, no need to map it twice

2021-03-09 19:41 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyRepository.java
> +public interface PropertyRepository extends CrudRepository<Property, Long>,
no need to implement this interface here

2021-03-09 19:59 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        List<Property> properties = propertyDslRepository
Do you mean `findMapLocations` function? If so, it was already on master. But I can make some changes if needed

2021-03-09 20:08 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        List<Property> properties = propertyDslRepository
Just leave this method as it was. No need to fetch additional fields here

2021-03-09 20:09 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +    public PropertiesLocationsResponseDto getMapLocations(String searchQuery,
https://github.com/PNUdev/communal-property-registry/pull/20/files#r590639788

2021-03-09 20:30 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/repository/dsl/QueryDslRepository.java
> +    default OrderSpecifier[] getOrderSpecifiers(Pageable pageable, Class<?> aClass) {
As I understand, this function used to extract order specifiers from Pageable object. But we don't need ordering so far, so we could remove this function.

2021-03-09 20:38 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +    public PropertiesLocationsResponseDto getMapLocations(String searchQuery,
Sorry, but I don't quite understand what does this link refers

2021-03-10 00:13 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/FlashMessageConstants.java
> +public enum FlashMessageConstants {
But shpalta if is based fully on server side templating. 
In scope of this PR, you're implementing REST endpoint.
That's why I ask.

2021-03-13 11:04 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        }};
empty ArrayList<>() will work as well

2021-03-13 11:16 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    public Property mapTupleToProperty(Tuple tuple) {
I think will be better `public Property mapToProperty(Tuple tuple) {` 
without Tuple, because we know it, this Tuple we accept as parameter in function

2021-03-13 13:31 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        }};
If no search parameters are provided, all records should be returned. I just decided to use double brace initialization, instead of adding this predicate in separate line

2021-03-13 15:46 UTC, MarrMika requested changes
1. Ctrl + Alt + O --- remove unused imports

2021-03-13 15:46 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/RestExceptionInterceptor.java
> +//    }
Commented? For what?

2021-03-13 15:46 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentService.java
> +
Collection<Long> id ? What is the purpose of using it? Why not just List?

2021-03-13 15:46 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentServiceImpl.java
> +    }
The same here with Collection

2021-03-13 15:46 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        }};
Collections.singletonList(add(property.id.isNotNull())) will help you

2021-03-13 15:46 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/api/PropertyController.java
> +import com.pnudev.communalpropertyregistry.domain.Property;
Unused import

2021-03-13 15:46 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyService.java
> +    void deleteById(Long id);
It is unused

2021-03-15 20:24 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/domain/Property.java
> +    }
👍

2021-03-15 20:24 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/RestExceptionInterceptor.java
> +}
You are using ServiceApiException for not found cases. So, replace it with the handling of 404 status code

2021-03-15 20:24 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentServiceImpl.java
> +        return attachmentRepository.findAttachmentsByPropertyIdIn(id);
List<Long> ids

2021-03-15 20:24 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentService.java
> +
List<Long> ids

2021-03-15 20:27 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                .categoryByPurposeName(categoryByPurpose.getName())
Create a separate method to check common logic with null setting

2021-03-15 20:28 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
Place it in the mapper package

2021-03-15 20:37 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/domain/Property.java
> +    }
👍

2021-03-15 21:10 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +
Nope, I meant other stuff. For now back as it was

2021-03-15 21:12 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/RestExceptionInterceptor.java
> +    public ErrorResponse generalError() {
Uncomment line 9 and add an exception in the method signature

2021-03-15 21:14 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/RestExceptionInterceptor.java
> +                .message(serviceApiException.getMessage())
From serviceApiException to handleServiceApiException

2021-03-15 21:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +
Return as it was previously

2021-03-16 20:42 UTC, MarrMika requested changes

2021-03-16 20:42 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                .lon(tuple.get(property.lon))
I see that this method is unused. Do we need it?

2021-03-16 20:42 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                                propertyTuple.get(property.id), attachments, attachmentCategories))
I think we can reuse validate() method as well

2021-03-16 20:42 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/repository/AttachmentRepository.java
> +    List<Attachment> findAttachmentsByPropertyIdIn(Collection<Long> propertyId);
I still see Collection. Please use List interface 
```
List<Long> propertyIds
```

2021-03-16 20:42 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
Remove `util` from path

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +    public List<CategoryByPurpose> finAllCategories() {
Remove this method and use the method above.
But move creation of `CategoryByPurposeResponseDto` from service to controller

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        // I decided to implement it this way in order to avoid creating additional method in repository
Remove this comment.
Use PR comments to communicate through the code.

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        predicates.add(property.id.isNotNull());
Do we need this initial predicate?

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                , propertyAttachments, attachmentCategories);
Formatting

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    private List<AttachmentResponseDto> createAttachmentResponseDto(Long propertyId,
`createAttachmentResponseDtos`

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    private AttachmentResponseDto createAttachmentResponseDto(List<Attachment> attachments,
This method should be located below the method, that calls it

2021-03-21 12:19 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                .filter((a) -> a.getAttachmentCategoryId().equals(attachmentCategory.getId())
again, do not name variables with single character
name it `attachment`
no need in parentheses

2021-03-21 12:27 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        predicates.add(property.id.isNotNull());
Yes, because in case if all of search parameters are apsent - this predicate will fetch all records.

2021-03-21 12:33 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        predicates.add(property.id.isNotNull());
Doesn't it work without it?

2021-03-21 12:51 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +        CategoryByPurposeResponseDto categoryByPurposeResponseDto = new CategoryByPurposeResponseDto(
Looks like using DTO is redundant for this controller
Please, refactor it

2021-03-21 12:54 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    private PropertyResponseDto buildPropertyResponseDto(Property property,
This method should be below the one, that is currently below it

2021-03-21 13:38 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/response/PropertyResponseDto.java
> +    private List<AttachmentResponseDto> attachments;
Check if UI correctly handles absence of this list

2021-03-21 17:30 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/dto/response/PropertyResponseDto.java
> +    private List<AttachmentResponseDto> attachments;
@SerhiiKlymchuk did a great work. So in case of absence, button 'Show attachment' have disabled state.

2021-03-21 17:33 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +        CategoryByPurposeResponseDto categoryByPurposeResponseDto = new CategoryByPurposeResponseDto(
It's not fixed

2021-03-21 17:39 UTC, Igor-Polatajko approved these changes
Good work!
Looks like it's ready to merge

2021-03-21 17:58 UTC, merged