[PNUDEV-6] Admin panel CRUD and visability settings of Property
PNUdev/communal-property-registry pull request #21
Opened 2021-03-04 17:27 UTC by vanya706

2021-03-05 09:00 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyDslRepositoryImpl.java
> +    }
Probably, you missed `@Autowired`

2021-03-05 09:02 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyDslRepositoryImpl.java
> +    }
Probably, you missed `@Autowired`

2021-03-05 09:07 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +public class PropertyController {
Set mapping to `/admin/properties`
And rename class to `PropertyAdminController`

2021-03-05 09:08 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +    @GetMapping("/index")
remove `/index`, let it be default controller mapping

2021-03-05 09:08 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +    public String index(@RequestParam(required = false) String q,
rename method to `findAll`

2021-03-05 09:09 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyController.java
> +        Page<Property> propertyPage = propertyService.findAll(q, categoryByPurposeId, propertyStatus, pageable);
rename variable to plural `propertiesPage`

2021-03-05 09:10 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +    public PropertyServiceImpl(Environment environment, PropertyDslRepository propertyDslRepository) {
`@Autowired`

2021-03-05 09:12 UTC, volodymyrvynnyk commented on src/main/resources/application.yaml
> +      key: ${TOMTOM_KEY:DITn9MLp6x2XRadsi2cp2h8RPKW6lExD}
Someone can still our key, repo is public...

2021-03-09 08:02 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/controller/PropertyAdminController.java
> +                pageable);
I do believe that you should place this logic in service

2021-03-09 08:07 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +                () -> new ServiceException("Didn't find property by id"));
Please rename all messages to Ukrainian

2021-03-09 08:10 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyAdminMapper.java
> +        return categoryByPurpose.orElseThrow(() -> new RuntimeException("Didn't find categoryByPurpose by id!"));
Please, change this message to Ukrainian, as well

2021-03-09 08:12 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +
You could implement this validations using Freemarker, but it's up to you.

2021-03-13 15:19 UTC, SerhiiKlymchuk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    }
I guess this should be `ServiceException`

2021-03-13 17:54 UTC, MrZenik approved these changes

2021-03-13 17:57 UTC, SerhiiKlymchuk approved these changes

2021-03-14 09:48 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +            return "redirect:/admin/properties";
theses lines are repeated in `if block` above
move it out of `if blockes`

2021-03-14 09:49 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +            propertyAdminService.save(propertyAdminFormDto, addresses.getAddresses().get(0));
better to keep this logic with `if address ...` in services

2021-03-14 09:54 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/dto/AddressResponseDto.java
> +    private List<AddressDto> addresses;
Why no just use `List<AddressDto>`? What is the purpose of this DTO?

2021-03-14 10:02 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/exception/CategoryByPurposeException.java
> +        super(message);
Don't understand why do we need this class, if we already have `ServiceAdminException`
Moreover, you just rewrote logic of intercepting `ServiceAdminException` for this new Exception, don't see any specific logic

2021-03-14 10:03 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ExceptionInterceptor.java
> +        return "redirect:/admin/properties";
These methods are almost the same as for `ServiceAdminException`, so no need of them

2021-03-14 10:04 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/exception/IllegalAddressAdminException.java
> +    }
Same as with `CategoryByPurposeException`, simply throw `ServiceAdminException` with specific message

2021-03-14 10:18 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +                address, environment.getProperty("application.tomtom.api.key")
Create a final field in this class `@Value("application.tomtom.api.key") String tomtomApiKey`
and use it

2021-03-14 10:24 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +        return new AddressResponseDto(addresses);
Why now just return list?

2021-03-14 10:25 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                () -> new CategoryByPurposeException("Категорії за призначенням не знайдено!"))));
Throw ServiceException

2021-03-14 10:26 UTC, volodymyrvynnyk requested changes
Some comments

2021-03-15 17:58 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +        }
This code is repeated, move it to private method

2021-03-15 17:59 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminService.java
> +    void save(PropertyAdminFormDto propertyAdminFormDto, AddressDto address);
rename this method to `create`

2021-03-15 18:00 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +    public String save(PropertyAdminFormDto propertyAdminFormDto,
rename method to `create` or `new`

2021-03-15 18:05 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +            } else {
Why are flashAttributes are used here? Don't simple `attributes` exist?
While updating, you should pass `id` of property to `/addresses` page

2021-03-15 18:08 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +
`Property propertyFromDb = repo.findById(id)
Property updatedProperty = propertyFromDb.toBuilder. <set fields from formDto> .build();`

2021-03-15 18:12 UTC, volodymyrvynnyk commented on src/main/resources/templates/admin/property/address.ftl
> +        <button type="submit" class="btn btn-primary mt-2" <#if propertyAdminFormDto.id??> formaction="/admin/properties/update/#{propertyAdminFormDto.id}"</#if>>Вибрати</button>
`propertyAdminFormDto.id` never exists, `id` of property for updating should be passed to this view in model or queryPath

2021-03-15 18:14 UTC, volodymyrvynnyk requested changes
Looks better, but not perfect 👯‍♀️

2021-03-15 19:30 UTC, MarrMika requested changes

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +
"Ви впевнені, що хочете видалити майно?"

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +        if (!model.containsAttribute("propertyAdminFormDto")) {
Rename method according to logic it holds

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +                    .eq(String.valueOf(Property.PropertyStatus.valueOf(propertyStatus))));
Property.PropertyStatus.valueOf(propertyStatus).name()

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +        }
Вказанa адресa є невірною!

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +        );
Define static final class variable TOM_TOM_URL = "https://api.tomtom.com/search/2/geocode/%s.json?" +
                        "storeResult=false&limit=20&lat=48.610742062164974f&lon=24.975710390429917&radius=30000&language=uk-UA&key=%s" and use over here in the method

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +    }
Create a separate class TomTomClient with a separate method and take this logic out. Inject TomTomClient as a bean in PropertyAdminServiceImpl

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +                .filter(c -> c.getId().equals(id)).findAny();
.findFirst() instaed of findAny()

2021-03-15 19:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/PropertyMapper.java
> +    }
"Категорію за призначенням не знайдено!"

2021-03-15 19:30 UTC, MarrMika commented on src/main/resources/templates/admin/property/address.ftl
> +    <form action="/admin/properties/save" method="post" id="address_form" onsubmit="setValues()" class="form-control">
Уточніть яку адресу ви хотіли ввести  з списку

2021-03-15 19:30 UTC, MarrMika commented on src/main/resources/templates/admin/property/form.ftl
> +                </div>
Take "Наприклад: вулиця Гуцульська, 18, Коломия, Івано-Франківська область, 78200" at the file level as varr. Use #assign

2021-03-15 19:30 UTC, MarrMika commented on src/main/resources/templates/admin/property/address.ftl
> +    }
Follow general style. Camel case or snake one

2021-03-15 19:30 UTC, MarrMika commented on src/main/resources/templates/admin/property/index.ftl
> +        </script>
Take this script out of <div class="container">

2021-03-15 19:30 UTC, MarrMika commented on src/main/resources/templates/admin/property/index.ftl
> +            <h1 class="text-center mt-5">
Idents propertiesPage.number == 0

2021-03-15 19:30 UTC, MarrMika commented on src/main/resources/templates/admin/property/index.ftl
> +                        </a>
Use Unicode of the back arrow

2021-03-16 15:09 UTC, volodymyrvynnyk approved these changes
Goog!

2021-03-16 20:30 UTC, MarrMika requested changes

2021-03-16 20:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ExceptionInterceptor.java
> +}
For me, it looks that we need some specific exception for property exception cases, because I don't think that it's good practice to redirect all exception actions to /admin/properties.

2021-03-16 20:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminService.java
> +
updateById, deleteById

2021-03-16 20:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/TomTomClient.java
> +        final String URL = String.format(TOM_TOM_URL, address, tomtomApiKey);
Please rename to processGetAdressRequest

2021-03-16 20:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/util/TomTomClient.java
> +
Add log about successful getting off the address. Something like "The address : [{}] was successfully found!"

2021-03-16 20:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +
Remove this one, there is no need to log this action

2021-03-16 20:30 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
> +        log.info("Method 'getAddresses' is going to finish work successfully!");
Remove this one, there is no need to log this action
You can leave a log message about the size of addresses that you get by a search address like below
```
log.info("Found [{}] addresses by input data: [{}]!", addresses.size(), address);
```

2021-03-16 21:24 UTC, MarrMika approved these changes
Great Job!!!

2021-03-17 21:17 UTC, Igor-Polatajko approved these changes
Great work!

2021-03-17 21:17 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/property/address.ftl
> +    function setValues() {
check if freemarker has the built in ability to format the number, without using js

2021-03-17 22:04 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +            } else {
Remove `else`
Your do `return` from `if`, so you don't need `else`

2021-03-17 22:04 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +                return "redirect:/admin/properties/addresses";
same

2021-03-17 23:55 UTC, merged