[PNUDEV-4] Implement marker locations REST endpoint
PNUdev/communal-property-registry pull request #22
Opened 2021-03-04 17:41 UTC by MrZenik

2021-03-04 18:42 UTC, vanya706 commented on pom.xml
> +                    <jdbcPassword>root</jdbcPassword>
There are should be in system enviroment, for example `${env.DB_URL}`

2021-03-04 18:49 UTC, vanya706 requested changes
Some comments

2021-03-04 19:27 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyLocationDslRepositoryImpl.java
>      public List<Tuple> findAll(Predicate... where) {
I think `PropertyLocationDslRepositoryImpl ` should return as type PropertyLocation but not Tuple

2021-03-04 19:39 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyLocationDslRepositoryImpl.java
> +                .select(property.all())
I think, use select by all fields in property is redundant in your case, because you need only lat, lon and id

2021-03-05 09:15 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyLocationResponseDto.java
> +    List<PropertyLocationDto> mapLocations;
make it private

2021-03-05 09:19 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyLocationDslRepositoryImpl.java
> +    public PropertyLocationDslRepositoryImpl(SQLQueryFactory queryFactory) {
@Autowired

2021-03-05 09:25 UTC, volodymyrvynnyk requested changes
Few comments

2021-03-05 13:24 UTC, vanya706 approved these changes
Good job!

2021-03-05 17:04 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/config/QuerydslConfig.java
> +
Let's make it more readable
```
return new SQLQueryFactory(
                new com.querydsl.sql.Configuration(new MySQLTemplates()),
                new TransactionAwareDataSourceProxy(dataSource)
);
```

2021-03-05 17:04 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/config/QuerydslConfig.java
> +
QueryDslConfig

2021-03-05 17:04 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/LocationServiceImpl.java
> +
Please, add some logs over here

2021-03-05 18:14 UTC, volodymyrvynnyk approved these changes
LGTM, but fix comments from @MarrMika

2021-03-05 18:35 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/LocationServiceImpl.java
> +
I do believe that you should place this function in mapper class. So please create `util.mapper.PropertyMapper` class and place this function there.

Also in that you should probably rename it to `mapToPropetyLocationDto`

2021-03-05 18:45 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyLocationDslRepositoryImpl.java
> +
Repository is responsible for interaction with database, there is no place to business logic.

Check out this 
[https://github.com/PNUdev/communal-property-registry/pull/22/commits/764223261dd25cf7fd80bb0ecf633b1150f8cd1a#r588567153](comment)

2021-03-06 10:38 UTC, MarrMika approved these changes

2021-03-06 11:06 UTC, Igor-Polatajko approved these changes
Good work!
Few comments related to moving this logic closer to other property related logic

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/LocationController.java
> +public class LocationController {
This should be under `PropertyController`

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/LocationController.java
> +    public PropertyLocationResponseDto getLocation(@Nullable @RequestParam(name = "q") String searchQuery,
`getMapLocations`

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/LocationService.java
> +    PropertyLocationResponseDto getLocation(String searchQuery, String propertyStatus,  Long categoryByPurposeId);
`getMapLocations`

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/PropertyLocationResponseDto.java
> +public class PropertyLocationResponseDto {
`PropertiesLocationsResponseDto`

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyLocationDslRepository.java
> +    PropertyLocationResponseDto findAll(Predicate... where);
`getMapLocations`

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/repository/PropertyLocationDslRepositoryImpl.java
> +    public PropertyLocationResponseDto findAll(Predicate... where) {
`findAllMapLocations`

2021-03-06 11:06 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/LocationServiceImpl.java
> +public class LocationServiceImpl implements LocationService{
I believe, this have to be under `PropertyService` as well

2021-03-06 12:07 UTC, Igor-Polatajko approved these changes

2021-03-06 12:07 UTC, merged