[PNUDEV-7] Admin panel CRUD of CategoryByPurpose
PNUdev/communal-property-registry pull request #23
Opened 2021-03-07 02:07 UTC by pikulo-kama

2021-03-07 18:35 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/dto/CategoryByPurposePaginationDto.java
> +public class CategoryByPurposePaginationDto {
rename to `CategoryByPurposePageDto`

2021-03-07 18:35 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +    public String getCategoryPage(@PathVariable("id") Long id, Model model) {
`getCategoryById`

2021-03-07 18:37 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +                "Category was successfully created");
Rewrite messages like this in Ukranian

2021-03-07 18:41 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/CategoryByPurposeRepository.java
> +                                                     PagingAndSortingRepository<CategoryByPurpose, Long> {
`PagingAndSortingRepository` extends `CrudRepository`, so no needs to extend this class from `CrudRepository` implicitly

2021-03-07 18:52 UTC, volodymyrvynnyk commented on src/main/resources/templates/admin/category/edit.ftl
> +
You can rename this file to `form.ftl`
and use it for both `create` and `update`
if `model` contains `category (to be update)` change `form action` to  `/admin/categories/update/${category.id}`
if no - change `form action` to `/admin/categories/create`

2021-03-07 18:52 UTC, volodymyrvynnyk commented on src/main/resources/templates/admin/category/edit.ftl
> +
And remove `new.ftl` as well

2021-03-07 18:59 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/dto/CategoryByPurposePaginationDto.java
> +    private Integer lastVisiblePage;
Delete this fields and look at comments below

2021-03-07 19:00 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +                .isLastPage(isLast)
```
.isFirstPage(pagination.isFirst())
.isLastPage(pagination.isLast())
```

2021-03-07 19:00 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +        }
And remove this stuff

2021-03-07 19:06 UTC, volodymyrvynnyk commented on src/main/resources/templates/admin/category/index.ftl
> +        </div>
https://github.com/PNUdev/shpalta-if/blob/master/src/main/resources/templates/admin/loginAttempts/index.ftl
Take a look how pagination is done here (lines 41-55)

2021-03-07 19:06 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +                .orElseThrow(() -> new ServiceException("Category by id not found"));
Messages should be in Ukrainian

2021-03-07 19:07 UTC, volodymyrvynnyk requested changes
Fix comments, please, if you have any questions, contact me in Telegram

2021-03-08 07:04 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +        model.addAttribute("pagination", pagination);
rename var also, `pagination` sound weird, use `page` or `categoriesPage`
same in service

2021-03-08 07:05 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +        validateCategoryName(categoryByPurposeDto.getName());
swap this methods calls in order not to call DB if `categoryName` is used

2021-03-08 07:08 UTC, volodymyrvynnyk approved these changes
Looks nice to me!

2021-03-08 13:20 UTC, MrZenik approved these changes

2021-03-09 13:07 UTC, MarrMika requested changes

2021-03-09 13:10 UTC, MarrMika commented
Nice work!
Please, update the photos in the description after changes just to keep data up to date

2021-03-09 20:00 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +    public String getAllCategories(Integer page, Model model) {
Please, check our internal methods naming convention over here: https://github.com/PNUdev/shpalta-if/blob/master/src/main/java/com/pnu/dev/shpaltaif/controller/CategoryAdminController.java

2021-03-09 20:01 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/CategoryByPurposeDto.java
> +public class CategoryByPurposeDto {
`CategoryByPurposeFormDto`

2021-03-09 20:01 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/dto/CategoryByPurposeDto.java
> +package com.pnudev.communalpropertyregistry.dto;
package com.pnudev.communalpropertyregistry.dto.**form**

2021-03-11 18:12 UTC, MarrMika commented
Please place the back button at all the views at the left top. I mean this one on the photo below
![image](https://user-images.githubusercontent.com/33421961/110834202-ef3e8a00-82a5-11eb-932d-824edf9b9a33.png)
And align these two buttons in the center
![image](https://user-images.githubusercontent.com/33421961/110834292-0c735880-82a6-11eb-97e7-f8e0dc8a4973.png)

2021-03-11 19:23 UTC, pikulo-kama commented
> Please place the back button at all the views at the left top. I mean this one on the photo below
> ![image](https://user-images.githubusercontent.com/33421961/110834202-ef3e8a00-82a5-11eb-932d-824edf9b9a33.png)
> And align these two buttons in the center
> ![image](https://user-images.githubusercontent.com/33421961/110834292-0c735880-82a6-11eb-97e7-f8e0dc8a4973.png)

Fixed

2021-03-12 17:04 UTC, MarrMika commented
1. Button 'Створити категорію' align in the center
2. Implement redirect  to "/admin/categories" after category creation
3. Place headers 'Створити категорія', 'Оновити категорію' at row with the back arrow button (I mean at the same level)
4. Hide pagination on UI if category list is empty
5. In the case of a category you want to create exists, give a user alert message and propose to provide a new category name. Don't redirect the user to an error page.
For this case, you can create a specific exception, eg. CategoryDuplicationException, and handle it separately from ServiceException. Take a look at  EmptyReportException handling in this example 
```
https://github.com/PNUdev/pnu-feedback/blob/master/src/main/java/com/pnu/dev/pnufeedback/exception/ExceptionInterceptor.java
```
6. Could you try to disable "Оновити" button until some changes were made with category name to prevent an extra call
7. Please try to get rid of  SerhiiKlymchuk's code in your PR. Interactive rebase must help you!

2021-03-13 13:02 UTC, vanya706 commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +    private final PropertyRepository propertyRepository;
new line...

2021-03-13 15:25 UTC, MarrMika requested changes
In case of flow delete/id -> deleteConfirmation-> exception("it is exists) -> error page -> return back-> delete confirmation model we are getting loop depencies with previous url
So, just handle this case by means of separate exception as CategoryDuplicationException

2021-03-13 15:25 UTC, MarrMika commented on src/main/resources/templates/admin/category/form.ftl
> +            </div>
make button disabled by default

2021-03-13 15:25 UTC, MarrMika commented on src/main/resources/templates/admin/category/form.ftl
> +
Refactor according to fact that button will be disabled by default

2021-03-13 21:41 UTC, MarrMika approved these changes
Good job!

2021-03-13 21:58 UTC, MarrMika commented
Please try to get rid of SerhiiKlymchuk's code in your PR. Interactive rebase must help you!

2021-03-15 14:28 UTC, SerhiiKlymchuk approved these changes
Looks nice!

2021-03-15 19:47 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/dto/form/CategoryByPurposeFormDto.java
> +}
Please, add @NotBlank, other way I can create a category with an empty name

2021-03-15 19:52 UTC, MarrMika commented on src/main/resources/templates/admin/category/form.ftl
> +                       <#if category?? >value="${category.name}"</#if> autofocus>
Add required attribute

2021-03-15 19:56 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +                         @Validated CategoryByPurposeFormDto categoryByPurposeDto,
updateById

2021-03-15 19:56 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +
deleteById

2021-03-15 19:57 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeService.java
> +
+ ById

2021-03-15 19:57 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +
+ ById

2021-03-15 19:58 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +
+ ById

2021-03-16 07:29 UTC, MarrMika commented
Please, clean commit history and leave only your commits

2021-03-21 18:23 UTC, MarrMika requested changes

2021-03-21 18:23 UTC, MarrMika commented on pom.xml
> +        </dependency>
No need to specify the version. By default, it will be the same as spring-boot-starter-parent

2021-03-21 18:23 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +    }
Do we need to have findAll() with pagination and without?

2021-03-21 18:23 UTC, MarrMika commented on src/main/resources/static/css/main.css
> +>>>>>>> origin/master
Resolve this conflict

2021-03-22 11:57 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +    }
I could replace `findAll()` like this `findAll(PageRequest.of(0, Integer.MAX_VALUE))`. But I'm not sure whether it will satisfy code styling requirements.

2021-03-23 06:36 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +    }
@Igor-Polatajko do we need here pagination? Seems no

2021-03-23 06:37 UTC, MarrMika commented
Comment history is not cleared yet. Please, fix it

2021-03-26 21:47 UTC, MarrMika approved these changes
Good job!

2021-03-27 19:21 UTC, Igor-Polatajko commented on src/main/resources/application.yaml
> +  profiles:
revert this change
it will break deployed app
`default` should be delault

2021-03-27 19:25 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/CategoryByPurposeServiceImpl.java
> +    public CategoryByPurposeResponseDto findAll() {
Why to change this?

2021-03-27 19:25 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/api/CategoryByPurposeController.java
> +        return categoryByPurposeService.findAll();
If there is no reason behind this change, than revert back

2021-03-27 19:25 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/config/WebConfig.java
> +        registry.addRedirectViewController("/admin", "/admin/properties");
👍

2021-03-27 19:37 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/CategoryByPurposeAdminController.java
> +        List<CategoryByPurpose> categoriesByPurpose = categoryByPurposeService
on one line

2021-03-27 19:39 UTC, Igor-Polatajko approved these changes
Looks nice
I like to see such progress on your skills

Fix the comment, test and merge it

2021-03-27 19:40 UTC, merged