Admin panel CRUD and visability settings of AttachmentCategory
PNUdev/communal-property-registry pull request #26
Opened 2021-03-12 15:40 UTC by MrZenik

![image](https://user-images.githubusercontent.com/70957784/110962574-cb3c8080-8359-11eb-9071-1b3bd26f50f2.png)
![image](https://user-images.githubusercontent.com/70957784/110962614-d5f71580-8359-11eb-9c2c-6bec65114fb3.png)
![image](https://user-images.githubusercontent.com/70957784/110962657-de4f5080-8359-11eb-894c-0a9c4567301e.png)
![image](https://user-images.githubusercontent.com/70957784/110962682-e5765e80-8359-11eb-9148-6781e1a5f235.png)

2021-03-13 11:30 UTC, vanya706 approved these changes
Looks good!

2021-03-13 16:52 UTC, SerhiiKlymchuk approved these changes

2021-03-14 11:33 UTC, MarrMika requested changes

2021-03-14 11:33 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentCategoryAdminController.java
> +        redirectAttributes.addFlashAttribute(SUCCESS_FLASH_MESSAGE.name(), "Категорію було успішно створено!");
Just "Категорію успішно створено!"

2021-03-14 11:33 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentCategoryAdminController.java
> +
without було

2021-03-14 11:33 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentCategoryAdminController.java
> +
without було

2021-03-14 11:33 UTC, MarrMika commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +
Please get rid of an extra call when nothing is changed

2021-03-14 11:33 UTC, MarrMika commented on src/main/resources/templates/admin/attachmentCategory/index.ftl
> +
Take it out from here and place it at the end of the file. Try it shorter like below
```
setTimeout(function () {
                $('#popup').alert('close');
            }, 5000);
```

2021-03-14 11:33 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +
Дію неможливо виконати, оскільки дана категорія активно використовується!

2021-03-15 18:17 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentCategoryAdminController.java
> +
А що було як було було? 🦞

2021-03-15 18:20 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/dto/AttachmentCategoryDto.java
> +    private boolean isPubliclyViewable;
That's the question of taste, but I'd prefer `isPublic` name for var
@MarrMika @Igor-Polatajko  what's your opinion?

2021-03-15 18:29 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/exception/AttachmentCategoryException.java
> +    }
Use `ServiceException` or `ServiceAdminException` instead, don't create custom for domain

2021-03-15 18:31 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryService.java
> +    void delete(Long id);
`deleteById` as you named method below  -  `updateById` and `findById`
Keep some convention in naming

2021-03-15 18:32 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +                ()-> new AttachmentCategoryException("Категорію не знайдено"));
throw `ServiceException` or  `ServiceAdminException`

2021-03-15 18:33 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        }
put these at the start of method

2021-03-15 18:33 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        AttachmentCategory attachmentCategory = findById(id);
rename to `attachmentCategoryFromDb` to better understanding

2021-03-15 18:34 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        attachmentCategory.setPubliclyViewable(attachmentCategoryDto.isPubliclyViewable());
can be replaced with  `toBuilder` but not necessary

2021-03-15 18:36 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/AttachmentCategoryRepository.java
> +    Boolean existsByName(String name);
create method `existsByNameAndIdNot(String name, Long id)` and you will simplify logic in service

2021-03-15 18:39 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        log.info("Attachment category {} was updated", attachmentCategoryDto.getName());
Add some text related old name of category
Because now it sounds like `Attachment category "that never existed" was updated`

2021-03-15 18:40 UTC, volodymyrvynnyk requested changes
Good job, few comments

2021-03-15 18:54 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/dto/AttachmentCategoryDto.java
> +    private boolean isPubliclyViewable;
Let's leave as it is

2021-03-16 15:26 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentCategoryAdminController.java
> +
🧐

2021-03-16 19:45 UTC, MarrMika requested changes

2021-03-16 19:45 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ExceptionInterceptor.java
> +}
For me, it was okay to keep the previous version with AttachmentCategoryException because it gives usability to handle all the exception cases  with AttachmentCategoryController and have graceful alert messagee

2021-03-16 19:45 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +    }
There is no need to log the old name it is non actual

2021-03-18 19:32 UTC, volodymyrvynnyk approved these changes
LGTM

2021-03-19 12:18 UTC, MarrMika requested changes
Please, clean commit history properly

2021-03-21 18:05 UTC, MarrMika approved these changes
Great Job!

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentCategoryAdminController.java
> +    @GetMapping("/new")
Please, stick to naming and url like here https://github.com/PNUdev/shpalta-if/blob/master/src/main/java/com/pnu/dev/shpaltaif/controller/CategoryAdminController.java

To have a consistency

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/exception/AttachmentCategoryException.java
> +public class AttachmentCategoryException extends ServiceException{
Formatting

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/PropertyAdminController.java
> +        model.addAttribute("categoriesByPurpose", categoryByPurposeService.findAll());
👍

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +    public Page<AttachmentCategory> findAll(Pageable pageable) {
Do we need pagination?
But, let it be

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        attachmentCategoryFromDb.setName(attachmentCategoryDto.getName());
`toBuilder()`

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +        let publiclyViewableBefore = <#if attachmentCategory.publiclyViewable> true <#else> false </#if>;
do not mix js and ftl
extract the variable at the top

`const isPubliclyViewable = <#if attachmentCategory.publiclyViewable> true <#else> false </#if>;`

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +        let newName = document.getElementById("name").value;
this should be `conts`

2021-03-21 19:36 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/index.ftl
> +<#else> <h2 class="text-center">Немає жодної категорії</h2>
new line after

2021-03-22 21:48 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        attachmentCategoryFromDb = AttachmentCategory.builder()
Looks like new item will be created insted of updating.
Use `toBuilder()`.
And do not reasign variables

2021-03-22 21:48 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +        }else{
fomatting

2021-03-23 21:10 UTC, Igor-Polatajko requested changes

2021-03-23 21:10 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +        }else {
Formatting

2021-03-23 21:10 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentCategoryServiceImpl.java
> +        attachmentCategoryFromDb.toBuilder()
This will not work.
Builder creates new instance.
Store it in the variable `updatedAttachmentCategory,` and then, save it to the db

2021-03-25 00:30 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +    const publiclyViewableBefore = <#if attachmentCategory.publiclyViewable> true
${attachmentCategory.publiclyViewable?then('true', 'false')}

2021-03-25 00:31 UTC, Igor-Polatajko commented on src/main/resources/templates/admin/attachmentCategory/edit.ftl
> +        } else {
`else if`

2021-03-25 00:32 UTC, Igor-Polatajko approved these changes
Few comments

2021-03-25 08:39 UTC, merged