[PNUDEV-8] Admin panel CRUD and visability settings of Attachment
PNUdev/communal-property-registry pull request #32
Opened 2021-03-20 21:17 UTC by vanya706

2021-03-21 12:10 UTC, MrZenik approved these changes

2021-03-21 12:14 UTC, SerhiiKlymchuk approved these changes

2021-03-21 14:29 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +@RequestMapping("/admin/attachments")
change mapping to `/admin/properties/{property_id}/attachments`

2021-03-21 14:30 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +@RequestMapping("/admin/attachments")
And fix other mappings in controller

2021-03-21 14:35 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/repository/AttachmentCategoryRepository.java
> +    Optional<AttachmentCategory> findById(Long id);
Not necessary to define these methods, they are defined in CrudRepository

2021-03-21 14:42 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentAdminServiceImpl.java
> +    }
It's wise to check whether property exists by id, in order not to show empty page

2021-03-21 14:45 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentAdminServiceImpl.java
> +        Attachment attachment = Attachment.builder()
Add code to verify whether attachment with `attachmentId` belongs to property with `propertyId`
can be done simply next way:
`Attachment attachmentFromDb = repository.findByIdAndPropertyId(attachmentId, propertyId).orElseThrow(attachment does not exists)`

2021-03-21 14:46 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentAdminServiceImpl.java
> +        Attachment attachment = Attachment.builder()
and then use `attachmentFromDb.toBuilder.....built()` and save it

2021-03-21 14:51 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/AttachmentMapper.java
> +        ).collect(Collectors.toList());
Not the best approach, now method call DB for `attachmentCategoryRepository.findById` N times, where N is size of the list. Try to change it by getting `List<AttachmentCategory>` for all `IDs`
`List<AttachmentCategory> categories = repo.findAllWhereIdIn(List<Long> ids)`

2021-03-21 14:53 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/AttachmentMapper.java
> +                .orElseThrow(() -> new PropertyAdminException("Категорії не існує!"));
Looks weird to throw `PropertyAdminException` when AttachmentCategory does not exist

2021-03-21 14:55 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/AttachmentMapper.java
> +        List<AttachmentCategory> attachmentCategories = attachmentCategoryRepository.findAll();
Transform it to `Map<CategoryId, AttachmentCategory>`

2021-03-21 14:56 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/AttachmentMapper.java
> +                attachment -> mapToAttachmentAdminDto(attachment, attachmentCategories)
`attachment -> mapToAttachmentAdminDto(attachment, attachmentCategoriesMap.get(attachment.getId))`

2021-03-21 14:57 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/AttachmentMapper.java
> +                                                       List<AttachmentCategory> attachmentCategories) {
Replace param `attachmentCategories` by `AttachmentCategory attachmentCategory`

2021-03-21 14:57 UTC, volodymyrvynnyk commented on src/main/java/com/pnudev/communalpropertyregistry/util/mapper/AttachmentMapper.java
> +        AttachmentCategory attachmentCategory = findAttachmentCategoryById(attachment.getAttachmentCategoryId(), attachmentCategories);
And lastly, delete this row

2021-03-21 14:59 UTC, volodymyrvynnyk requested changes
Let's code 👯‍♀️

2021-03-21 18:26 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/repository/AttachmentCategoryRepository.java
> +    Optional<AttachmentCategory> findById(Long id);
the method findAll() can be here otherwise you need to cast it

2021-03-21 18:28 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/repository/AttachmentRepository.java
> +    void deleteAllByPropertyId(@Param("propertyId") Long propertyId);
Try to execute it without defining a custom query. Try delete line 16

2021-03-21 18:43 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +    }
Id is not used in this method

2021-03-21 18:45 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +    }
Id is not used in this method

2021-03-21 18:50 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/AttachmentAdminServiceImpl.java
> +        }
Could I ask you to create a specific exception for attachment entity actions and in the case  it will be thrown redirect to /admin/attachments/property/{id} instead of /admin/properties

2021-03-22 19:13 UTC, volodymyrvynnyk approved these changes
LGTM

2021-03-23 07:10 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +        return "redirect:/admin/properties/" + propertyId + "/attachments";
Please assign it as a static final variable and use String.format()

2021-03-23 07:10 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +    }
Please assign it as a static final variable and use String.format()

2021-03-23 07:11 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +    }
Here is the same, reuse new variable

2021-03-23 07:26 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/exception/ExceptionInterceptor.java
> +    public String attachmentAdminException(AttachmentAdminException attachmentAdminException, RedirectAttributes redirectAttributes) {
from attachmentAdminException to handleAttachmentAdminException

2021-03-23 07:36 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyAdminServiceImpl.java
>      @Override
Please, add @Transactional annotationon

2021-03-24 19:04 UTC, MarrMika commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +
When I set fake atachmentId  I get an alert about the successful deletion. Please handle not found case for attachment by atachmentId

2021-03-25 20:41 UTC, MarrMika approved these changes
Good job!

2021-03-26 09:28 UTC, Igor-Polatajko approved these changes

2021-03-26 09:28 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/controller/admin/AttachmentAdminController.java
> +    @GetMapping("/update/{attachment_id}")
lets keep URLs and methods naming like in this class
https://github.com/PNUdev/shpalta-if/blob/master/src/main/java/com/pnu/dev/shpaltaif/controller/CategoryAdminController.java

2021-03-26 21:48 UTC, merged