[PNUDEV-5] Implement EXCEL reports
PNUdev/communal-property-registry pull request #44
Opened 2021-03-30 21:03 UTC by SerhiiKlymchuk

- Public report - (Only public fields are included)
![public_report](https://user-images.githubusercontent.com/72470924/113456480-04768680-9416-11eb-8647-ce4cfc4927bd.png)

- Full private report (All fields are included)
![full_report](https://user-images.githubusercontent.com/72470924/113456490-0a6c6780-9416-11eb-9f5c-a9f7df02e437.png)

- **Some changes to UI at 'category by purpose' admin block were made.**

- No content
![empty](https://user-images.githubusercontent.com/72470924/113456552-296af980-9416-11eb-966d-bf1d46034a94.png)

- With content
![with_content](https://user-images.githubusercontent.com/72470924/113456570-3851ac00-9416-11eb-8571-e5c17ad3a036.png)

2021-04-02 22:07 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +                    Field[] allFields = property.getClass().getDeclaredFields();
Avoid reflection, if possible.
We know the field names, also headers are hardcoded.
But I appreciate this approach, it looks cool, though only for library.

2021-04-02 22:07 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/ExcelReportBuilderServiceImpl.java
> +        return propertyService.findPropertiesBySearchQuery(searchQuery, propertyStatus,
Use can create `Pageable.unpaged()` here to get all records. But check if it works, because there was a bug related to it.

2021-04-02 22:07 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/FullExcelReportBuilderServiceImpl.java
> +        return propertyService.findPropertiesWithAllFieldsBySearchQuery(searchQuery, propertyStatus,
same here

2021-04-02 22:07 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        return new PageImpl<>(content, pageable, propertyPages.getTotalElements());
you can avoid recreating of page here.
Just pass Page to the mapper. Page has its own `map` method for use cases like this

2021-04-03 09:04 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/ExcelReportBuilderServiceImpl.java
> +        return propertyService.findPropertiesBySearchQuery(searchQuery, propertyStatus,
I have tried to pass `Pageable.unpaged()` but it doesn't have `.pageSize()` method, so error in `DslRepository` was thrown.

2021-04-03 09:06 UTC, pikulo-kama commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        return new PageImpl<>(content, pageable, propertyPages.getTotalElements());
I decided to make it that way, because during mapping of list of elements there will be less calls to the database. But I could change mapping if needed.

2021-04-03 10:07 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/PropertyServiceImpl.java
> +        return new PageImpl<>(content, pageable, propertyPages.getTotalElements());
Not sure, that I understand what you mean.
`Map` any way will be applied to each element individually.
Using it on `map` rather then on string will be just better syntax

2021-04-03 10:13 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +                "Довгота", "Широта", "Назва", "Назва категорії", "Статус", "Площа", "Площа для продажу",
`BASE_HEADERS`
They should he assigned, in the place, where constant is created

2021-04-03 10:17 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +        headers.addAll(getAttachmentHeaders());
Then, create new list from BASE_HEADERS and results from this method

2021-04-03 10:17 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +        } else {
No need in else

2021-04-03 12:03 UTC, Igor-Polatajko requested changes

2021-04-03 12:03 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +    private static final List<String> BASE_HEADERS = Arrays.asList("ID", "Посилання на зображення", "Адреса",
move to top

2021-04-03 12:03 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +    private HSSFWorkbook workbook;
do not reasign fields
create variables in the place of usage

2021-04-03 12:03 UTC, Igor-Polatajko commented on src/main/java/com/pnudev/communalpropertyregistry/service/AbstractExcelReportBuilderService.java
> +    @SneakyThrows
remove this annotation

2021-04-03 12:20 UTC, vanya706 approved these changes

2021-04-03 12:37 UTC, vanya706 approved these changes
good job!

2021-04-03 15:48 UTC, Igor-Polatajko approved these changes

2021-04-03 15:49 UTC, merged